name: Cloud Functions

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  FUNCTION_NAME: mimo-capital-xero-${{ github.ref_name }}
  PUBLIC_URL: https://us-central1-mimo-capital-1.cloudfunctions.net/mimo-capital-xero-${{ github.ref_name }}
  GCP_SA: integration-1@mimo-capital-1.iam.gserviceaccount.com

  ENV_FILE: env.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci

      - run: tsc --project tsconfig.build.json

      - run: |
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json
          cp tenants.ndjson dist/tenants.json

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: |
          echo "XERO_CLIENT_ID: ${{ secrets.XERO_CLIENT_ID }}" >> ${{ env.ENV_FILE }}
          echo "XERO_CLIENT_SECRET: ${{ secrets.XERO_CLIENT_SECRET }}" >> ${{ env.ENV_FILE }}

          echo "PUBLIC_URL: ${{ env.PUBLIC_URL }}" >> ${{ env.ENV_FILE }}

      - run: >-
          gcloud functions deploy ${{ env.FUNCTION_NAME }}
          --entry-point=main
          --source=dist
          --region=us-central1
          --timeout=530
          --memory=1024MB
          --runtime=nodejs16
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --allow-unauthenticated
          --env-vars-file=${{ env.ENV_FILE }}
